server:
  servlet:
    context-path: /auth
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://106.12.27.199:5432/agcim
    username: agcim
    password: agcim123
    driver-class-name: org.postgresql.Driver
  redis:
    database: 0
    host: 106.12.27.199
    password: agcim-2020
    timeout: 8000
    port: 6379
jasypt:
  encryptor:
    password: abc123